
const D=window.RLI_DATA;let current="agg_nacional",networkCurrent="agg_nacional";const $=s=>document.querySelector(s);
function esc(s){return String(s??"").replace(/[&<>]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[m]))}
const choices={panorama:[["agg_nacional","Todas as leis"],["agg_federal","Leis nacionais (federais)"],["agg_estadual","Todas as leis estaduais"],["agg_municipal","Todas as leis municipais"]],regiao:[["reg_norte","Norte"],["reg_nordeste","Nordeste"],["reg_centro_oeste","Centro-Oeste"],["reg_sudeste","Sudeste"],["reg_sul","Sul"]],lei:D.laws.map(x=>[x.id,`${x.numero} — ${x.nome}${x.uf?` (${x.uf})`:''}`])};
function norm(s){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function filteredItems(type,q){let items=choices[type];return type==="lei"&&q?items.filter(x=>norm(x[1]).includes(norm(q))):items}
function renderChoices(){let type=$("#viewType").value,items=filteredItems(type,$("#lawSearch").value);$("#viewChoice").innerHTML=items.length?items.map(x=>`<option value="${x[0]}">${esc(x[1])}</option>`).join(''):'<option value="">Nenhuma lei encontrada</option>';if(items.length)show(items[0][0])}
function populateChoices(){let type=$("#viewType").value;$("#lawSearchWrap").hidden=type!=="lei";if(type!=="lei")$("#lawSearch").value="";$("#choiceLabel").textContent=type==="lei"?"3. Escolha a lei":type==="regiao"?"2. Escolha a região (somente leis estaduais)":"2. Escolha a abrangência";renderChoices()}
function renderNetworkChoices(){let type=$("#networkViewType").value,items=filteredItems(type,$("#networkLawSearch").value);$("#networkViewChoice").innerHTML=items.length?items.map(x=>`<option value="${x[0]}">${esc(x[1])}</option>`).join(''):'<option value="">Nenhuma lei encontrada</option>';if(items.length)showNetwork(items[0][0])}
function populateNetworkChoices(){let type=$("#networkViewType").value;$("#networkLawSearchWrap").hidden=type!=="lei";if(type!=="lei")$("#networkLawSearch").value="";$("#networkChoiceLabel").textContent=type==="lei"?"3. Escolha a lei":type==="regiao"?"2. Escolha a região (somente leis estaduais)":"2. Escolha a abrangência";renderNetworkChoices()}
function show(id){current=id;let c=D.clouds[id];if(!c)return;$("#cloudTitle").textContent=c.title;$("#cloudSub").textContent=c.subtitle;$("#badge").textContent=c.type;$("#lawCount").textContent=c.count;$("#termCount").textContent=c.terms.toLocaleString("pt-BR");let scale=Math.min(1,$("#cloud").clientWidth/780);$("#cloud").innerHTML=c.words.map(w=>`<span class="word ${w.rotate?"rot":""}" title="${w.freq} ocorrências" style="left:${w.x}%;top:${w.y}%;font-size:${(w.size*scale).toFixed(1)}px;color:${w.color}">${esc(w.word)}</span>`).join("");$("#downloadCloud").href=`png/${id}.png`;$("#downloadCloud").download=`nuvem_${id}.png`;let law=D.laws.find(x=>x.id===id);$("#details").innerHTML=law?`<span>${esc(law.regiao)} · ${esc(law.fonte)}</span><a href="${esc(law.url)}" target="_blank" rel="noopener">Acessar texto oficial ↗</a>`:`<span>${c.count} norma(s) neste recorte</span><span>Frequência absoluta após limpeza lexical</span>`}
function showNetwork(id){networkCurrent=id;let c=D.clouds[id],n=D.networks[id].article,colors=['#52b96b','#e3a83b','#5a8ec8','#d36f6f','#8c72b8','#4e9c92'];$("#networkTitle").textContent=c.title;$("#networkLawCount").textContent=c.count;$("#networkNodeCount").textContent=n.nodes.length;$("#netUnits").textContent=n.metrics.units;$("#netDensity").textContent=n.metrics.density;$("#netDegree").textContent=n.metrics.mean_degree;$("#netCommunities").textContent=n.metrics.communities;if(!n.nodes.length){$("#networkSvg").innerHTML='<text x="50%" y="50%" text-anchor="middle">Rede insuficiente para este recorte.</text>';return}let W=900,H=610,node=Object.fromEntries(n.nodes.map(x=>[x.id,x]));let edges=n.edges.map(e=>`<line x1="${node[e.source].x/100*W}" y1="${node[e.source].y/100*H}" x2="${node[e.target].x/100*W}" y2="${node[e.target].y/100*H}" stroke="#9aaba0" stroke-opacity="${.18+.65*e.association}" stroke-width="${1+5*e.association}"><title>${esc(node[e.source].label)} ↔ ${esc(node[e.target].label)} · associação ${e.association}</title></line>`).join('');let maxS=Math.max(...n.nodes.map(x=>x.strength));let nodes=n.nodes.map(x=>{let r=7+15*x.strength/maxS,c=colors[(x.community-1)%colors.length];return `<g transform="translate(${x.x/100*W},${x.y/100*H})"><circle r="${r}" fill="${c}" stroke="#fff" stroke-width="2"><title>${esc(x.label)} · força ${x.strength} · grau ${x.degree} · intermediação ${x.betweenness}</title></circle><text y="${r+14}" text-anchor="middle">${esc(x.label)}</text></g>`}).join('');$("#networkSvg").innerHTML=edges+nodes}
$("#viewType").addEventListener('change',populateChoices);$("#viewChoice").addEventListener('change',e=>e.target.value&&show(e.target.value));$("#lawSearch").addEventListener('input',renderChoices);$("#networkViewType").addEventListener('change',populateNetworkChoices);$("#networkViewChoice").addEventListener('change',e=>e.target.value&&showNetwork(e.target.value));$("#networkLawSearch").addEventListener('input',renderNetworkChoices);populateChoices();populateNetworkChoices();let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>show(current),120)});

